import os
from fpdf import FPDF
from app.db.models import Meeting

class MeetingPDF(FPDF):
    def header(self):
        # Logo
        # The script is in backend/app/services, so static is at ../../static
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        logo_path = os.path.join(base_dir, 'static', 'images', 'MeetIQ_logo.png')
        if os.path.exists(logo_path):
            self.image(logo_path, 10, 8, 25)
        
        # Professional header title
        self.set_font('helvetica', 'B', 15)
        self.cell(40)
        self.cell(0, 10, 'MeetIQ - Meeting Summary Report', border=0, align='R', new_x="LMARGIN", new_y="NEXT")
        
        # 🔴 CRITICAL FIX: Push the cursor down past the logo! (Logo is at Y=8, height=25)
        self.set_y(38)
        
        # Horizontal divider (drawn just above the new text cursor)
        self.set_draw_color(200, 200, 200)
        self.line(10, 36, 200, 36)
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        
        # Confidentiality notice
        self.cell(100, 10, 'CONFIDENTIAL: Generated by MeetIQ AI', border=0, align='L')
        # Page number
        self.cell(0, 10, f'Page {self.page_no()} / {{nb}}', border=0, align='R')

def generate_meeting_pdf(meeting: Meeting) -> bytes:
    pdf = MeetingPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Title
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_x(10)
    # 🔴 CRITICAL FIX: Use cell with line breaks instead of multi_cell to prevent floating text
    pdf.cell(0, 10, "Meeting Details", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
    
    # Metadata
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    date_str = meeting.created_at.strftime('%Y-%m-%d %H:%M') if meeting.created_at else "Unknown Date"
    platform = meeting.platform.capitalize() if meeting.platform else "Unknown Platform"
    pdf.cell(0, 8, f"Date: {date_str}  |  Platform: {platform}", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    pdf.set_text_color(0, 0, 0)
    
    transcript = meeting.transcript or {}
    
    # Summary
    if transcript.get('summary'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, "Summary", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('helvetica', '', 11)
        pdf.set_x(10)
        pdf.multi_cell(0, 6, transcript['summary'])
        pdf.ln(5)
        
    # Key Points
    if transcript.get('key_points') and len(transcript['key_points']) > 0:
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, "Key Points", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('helvetica', '', 11)
        for pt in transcript['key_points']:
            pdf.set_x(10) # Good! This prevents the margin crash.
            pdf.multi_cell(0, 6, f"- {pt}")
        pdf.ln(5)
        
    # Action Items
    if transcript.get('action_items') and len(transcript['action_items']) > 0:
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, "Action Items", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('helvetica', '', 11)
        for item in transcript['action_items']:
            owner = item.get('owner', 'Unspecified')
            task = item.get('item', '')
            pdf.set_x(10) # Good!
            pdf.multi_cell(0, 6, f"- [{owner}] {task}")
        pdf.ln(5)
        
    # Conclusion
    if transcript.get('conclusion'):
        pdf.set_font('helvetica', 'B', 14)
        pdf.cell(0, 10, "Conclusion", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
        pdf.set_font('helvetica', '', 11)
        pdf.set_x(10)
        pdf.multi_cell(0, 6, transcript['conclusion'])
        pdf.ln(5)

    return bytes(pdf.output())


# import os
# from fpdf import FPDF
# from app.db.models import Meeting

# class MeetingPDF(FPDF):
#     def header(self):
#         # Logo
#         # The script is in backend/app/services, so static is at ../../static
#         base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
#         logo_path = os.path.join(base_dir, 'static', 'images', 'MeetIQ_logo.png.png')
#         if os.path.exists(logo_path):
#             self.image(logo_path, 10, 8, 25)
        
#         # Professional header title
#         self.set_font('helvetica', 'B', 15)
#         self.cell(40)
#         self.cell(0, 10, 'MeetIQ - Meeting Summary Report', border=0, align='R', new_x="LMARGIN", new_y="NEXT")
        
#         # Horizontal divider
#         self.set_draw_color(200, 200, 200)
#         self.line(10, 22, 200, 22)
#         self.ln(5)

#     def footer(self):
#         # Position at 1.5 cm from bottom
#         self.set_y(-15)
#         self.set_font('helvetica', 'I', 8)
#         self.set_text_color(128, 128, 128)
        
#         # Confidentiality notice
#         self.cell(100, 10, 'CONFIDENTIAL: Generated by MeetIQ AI', border=0, align='L')
#         # Page number
#         self.cell(0, 10, f'Page {self.page_no()} / {{nb}}', border=0, align='R')

# def generate_meeting_pdf(meeting: Meeting) -> bytes:
#     pdf = MeetingPDF()
#     pdf.alias_nb_pages()
#     pdf.add_page()
    
#     # Title
#     pdf.set_font('helvetica', 'B', 16)
#     pdf.set_x(10)
#     pdf.multi_cell(0, 10, "Meeting Details")
    
#     # Metadata
#     pdf.set_font('helvetica', '', 10)
#     pdf.set_text_color(100, 100, 100)
#     date_str = meeting.created_at.strftime('%Y-%m-%d %H:%M') if meeting.created_at else "Unknown Date"
#     platform = meeting.platform.capitalize() if meeting.platform else "Unknown Platform"
#     pdf.cell(0, 8, f"Date: {date_str}  |  Platform: {platform}", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
#     pdf.ln(4)
    
#     pdf.set_text_color(0, 0, 0)
    
#     transcript = meeting.transcript or {}
    
#     # Summary
#     if transcript.get('summary'):
#         pdf.set_font('helvetica', 'B', 14)
#         pdf.cell(0, 10, "Summary", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
#         pdf.set_font('helvetica', '', 11)
#         pdf.set_x(10)
#         pdf.multi_cell(0, 6, transcript['summary'])
#         pdf.ln(5)
        
#     # Key Points
#     if transcript.get('key_points') and len(transcript['key_points']) > 0:
#         pdf.set_font('helvetica', 'B', 14)
#         pdf.cell(0, 10, "Key Points", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
#         pdf.set_font('helvetica', '', 11)
#         for pt in transcript['key_points']:
#             pdf.set_x(10)
#             pdf.multi_cell(0, 6, f"- {pt}")
#         pdf.ln(5)
        
#     # Action Items
#     if transcript.get('action_items') and len(transcript['action_items']) > 0:
#         pdf.set_font('helvetica', 'B', 14)
#         pdf.cell(0, 10, "Action Items", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
#         pdf.set_font('helvetica', '', 11)
#         for item in transcript['action_items']:
#             owner = item.get('owner', 'Unspecified')
#             task = item.get('item', '')
#             pdf.set_x(10)
#             pdf.multi_cell(0, 6, f"- [{owner}] {task}")
#         pdf.ln(5)
        
#     # Conclusion
#     if transcript.get('conclusion'):
#         pdf.set_font('helvetica', 'B', 14)
#         pdf.cell(0, 10, "Conclusion", border=0, align='L', new_x="LMARGIN", new_y="NEXT")
#         pdf.set_font('helvetica', '', 11)
#         pdf.set_x(10)
#         pdf.multi_cell(0, 6, transcript['conclusion'])
#         pdf.ln(5)

#     return bytes(pdf.output())
