"""initial_schema

Revision ID: 475e9ee29ad9
Revises: 
Create Date: 2026-08-16 19:13:02.602100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '475e9ee29ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.execute('TRUNCATE TABLE meeting_chunks CASCADE;')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('meeting_chunks', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('meeting_chunks', 'speakers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'timestamp_start',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'timestamp_end',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=False,
               postgresql_using="embedding::vector(768)")
    op.drop_index('meeting_chunks_embedding_idx', table_name='meeting_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('meeting_chunks_meeting_id_idx', table_name='meeting_chunks')
    op.add_column('meetings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('meetings', 'meeting_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('meetings', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('meetings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::text"))
    op.alter_column('meetings', 'recording_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('meetings', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'meetings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.alter_column('meetings', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meetings', 'recording_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::text"))
    op.alter_column('meetings', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('meetings', 'meeting_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('meetings', 'user_id')
    op.create_index('meeting_chunks_meeting_id_idx', 'meeting_chunks', ['meeting_id'], unique=False)
    op.create_index('meeting_chunks_embedding_idx', 'meeting_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('meeting_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=False)
    op.alter_column('meeting_chunks', 'timestamp_end',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'timestamp_start',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'speakers',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('meeting_chunks', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
